/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'bio' : string,
  'name' : string,
  'socials' : Array<string>,
}
export interface Event {
  'id' : string,
  'venue' : string,
  'city' : string,
  'date' : Time,
  'ticketLink' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface Release {
  'id' : string,
  'title' : string,
  'date' : Time,
  'streamingLinks' : Array<string>,
  'coverImage' : ExternalBlob,
}
export type Time = bigint;
export interface Track { 'id' : string, 'title' : string, 'releaseId' : string }
export interface UserPlan {
  'id' : string,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'platformLink' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvent' : ActorMethod<[Event], undefined>,
  'addGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'addRelease' : ActorMethod<[Release], undefined>,
  'addTrack' : ActorMethod<[Track], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserPlan' : ActorMethod<[string], undefined>,
  'createUserPlan' : ActorMethod<[UserPlan], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteRelease' : ActorMethod<[string], undefined>,
  'deleteTrack' : ActorMethod<[string], undefined>,
  'deleteUserPlan' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllReleases' : ActorMethod<[], Array<Release>>,
  'getAllTracks' : ActorMethod<[], Array<Track>>,
  'getAllUserPlans' : ActorMethod<[], [] | [Array<UserPlan>]>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserPlan' : ActorMethod<[], [] | [UserPlan]>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getGalleryItem' : ActorMethod<[string], [] | [GalleryItem]>,
  'getProfile' : ActorMethod<[], [] | [ArtistProfile]>,
  'getRelease' : ActorMethod<[string], [] | [Release]>,
  'getTrack' : ActorMethod<[string], [] | [Track]>,
  'getUserPlan' : ActorMethod<[string], [] | [UserPlan]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string], [] | [Video]>,
  'initializeArtist' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'updateProfile' : ActorMethod<[ArtistProfile], undefined>,
  'updateRelease' : ActorMethod<[Release], undefined>,
  'updateTrack' : ActorMethod<[Track], undefined>,
  'updateUserPlan' : ActorMethod<[UserPlan], undefined>,
  'updateVideo' : ActorMethod<[Video], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];