/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Event = IDL.Record({
  'id' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : Time,
  'ticketLink' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const Release = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'streamingLinks' : IDL.Vec(IDL.Text),
  'coverImage' : ExternalBlob,
});
export const Track = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'releaseId' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'platformLink' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserPlan = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ArtistProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'socials' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func([Event], [], []),
  'addGalleryItem' : IDL.Func([GalleryItem], [], []),
  'addRelease' : IDL.Func([Release], [], []),
  'addTrack' : IDL.Func([Track], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserPlan' : IDL.Func([IDL.Text], [], []),
  'createUserPlan' : IDL.Func([UserPlan], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteRelease' : IDL.Func([IDL.Text], [], []),
  'deleteTrack' : IDL.Func([IDL.Text], [], []),
  'deleteUserPlan' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getAllTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'getAllUserPlans' : IDL.Func([], [IDL.Opt(IDL.Vec(UserPlan))], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserPlan' : IDL.Func([], [IDL.Opt(UserPlan)], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Text], [IDL.Opt(GalleryItem)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
  'getRelease' : IDL.Func([IDL.Text], [IDL.Opt(Release)], ['query']),
  'getTrack' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
  'getUserPlan' : IDL.Func([IDL.Text], [IDL.Opt(UserPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
  'initializeArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateGalleryItem' : IDL.Func([GalleryItem], [], []),
  'updateProfile' : IDL.Func([ArtistProfile], [], []),
  'updateRelease' : IDL.Func([Release], [], []),
  'updateTrack' : IDL.Func([Track], [], []),
  'updateUserPlan' : IDL.Func([UserPlan], [], []),
  'updateVideo' : IDL.Func([Video], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Event = IDL.Record({
    'id' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : Time,
    'ticketLink' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Release = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'streamingLinks' : IDL.Vec(IDL.Text),
    'coverImage' : ExternalBlob,
  });
  const Track = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'releaseId' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'platformLink' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserPlan = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ArtistProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'socials' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func([Event], [], []),
    'addGalleryItem' : IDL.Func([GalleryItem], [], []),
    'addRelease' : IDL.Func([Release], [], []),
    'addTrack' : IDL.Func([Track], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserPlan' : IDL.Func([IDL.Text], [], []),
    'createUserPlan' : IDL.Func([UserPlan], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteRelease' : IDL.Func([IDL.Text], [], []),
    'deleteTrack' : IDL.Func([IDL.Text], [], []),
    'deleteUserPlan' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getAllTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'getAllUserPlans' : IDL.Func([], [IDL.Opt(IDL.Vec(UserPlan))], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserPlan' : IDL.Func([], [IDL.Opt(UserPlan)], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getGalleryItem' : IDL.Func([IDL.Text], [IDL.Opt(GalleryItem)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
    'getRelease' : IDL.Func([IDL.Text], [IDL.Opt(Release)], ['query']),
    'getTrack' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
    'getUserPlan' : IDL.Func([IDL.Text], [IDL.Opt(UserPlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
    'initializeArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateGalleryItem' : IDL.Func([GalleryItem], [], []),
    'updateProfile' : IDL.Func([ArtistProfile], [], []),
    'updateRelease' : IDL.Func([Release], [], []),
    'updateTrack' : IDL.Func([Track], [], []),
    'updateUserPlan' : IDL.Func([UserPlan], [], []),
    'updateVideo' : IDL.Func([Video], [], []),
  });
};

export const init = ({ IDL }) => { return []; };